databases:
  - name: ninety_nine_cats
    databaseName: ninety_nine_cats_db
    user: ninety_nine_cats_user

services:
  - type: web
    name: ninety_nine_cats
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ninety_nine_cats
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false