databases:
  - name: ninety-nine-cats-db
    databaseName: ninety_nine_cats_db_e9v6
    user: ninety_nine_cats_db_e9v6_user

services:
  - type: web
    name: ninety_nine_cats
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ninety-nine-cats-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false