databases:
  - name: cats
    databaseName: cats
    user: cats

services:
  - type: web
    name: cats
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cats
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false